### PR TITLE
modify expression-language requirement

### PR DESCRIPTION
**Pull request by nicolasThal**

### CODE REVIEW

**Comment by bytehead** [comment]
Do you need `symfony/expression-language` in version `3.x`?

**Comment by nicolasThal** [comment]
Sorry, I didn't took time to explain my needs..

I wanted to use the bundle with a sf3.1 installation, and the translation component was creating some conflicts during the composer installation.

**Comment by bytehead** [comment]
Thank you!

**Comment by bytehead** [comment]
https://github.com/1up-lab/OneupAclBundle/pull/33 is also an open PR for Symfony 3 compatibility.  Maybe you can check [`feature/symfony3`](https://github.com/1up-lab/OneupAclBundle/tree/feature/symfony3) as well?

**Pull request merged**
