### PR TITLE
Symfony 3 support

### PR DESCRIPTION
**Pull request by vrnagy**
All test pass on all currently supported Symfony versions.

### CODE REVIEW

**Comment by vrnagy** [comment]
@bytehead can You please review?

Thanks

**Comment by bytehead** [comment]
Thanks @vrnagy, I will review this.

**Comment by vrnagy** [comment]
Sorry to distub again.
Maybe You have some free time to check this?
I would like to upgrade to symfony 3 and this issue is the only release blocker now.

Thanks

**Comment by bytehead** [comment]
Sorry @vrnagy for my delay!
I've opened a branch [`feature/symfony3`](https://github.com/1up-lab/OneupAclBundle/tree/feature/symfony3) which you can use in your `composer.json` for now until it's merged into master. Is that ok for you?

**Comment by vrnagy** [comment]
Great!

Thank You

**Comment by bytehead** [comment]
No worries, you're welcome! I'm sorry, I don't have that much free time right now to actually dig into this. I'll keep you updated.

**Comment by bytehead** [comment]
@vrnagy Did you use [`feature/symfony3`](https://github.com/1up-lab/OneupAclBundle/tree/feature/symfony3) already in production?

**Comment by vrnagy** [comment]
Yes, since You created the branch, without any issue

**Comment by bytehead** [comment]
Cool! So I'll merge it and create a new release (probably `1.0.0`). 
/cc @helmuthva

**Comment by bytehead** [comment]
Thank you very much! [`1.0.0`](https://github.com/1up-lab/OneupAclBundle/releases/tag/1.0.0) is now available!

**Pull request merged**
